### ISSUE TITLE
无法正常推送动态，且监控列表有概率无法正常发出

### ISSUE THREAD

**Issue by KomeijiRan** [Nekoer/mirai-plugins-bilibili#6]
如题，设置监控推送碧蓝航线（233114659）和碧蓝海事局（205889201）的动态，但没有正常推送，关闭mcl添加设置监控我自己的b站账号，能够正常推送我自己发的动态，再删除我的账号恢复之前的设置之后依然无法推送碧蓝航线的动态。
另，使用/rss list指令有概率无法发送监控列表，如下图。
![图片](https://user-images.githubusercontent.com/96311761/179152408-018a5f26-8a2f-444d-ab9a-ddf145044871.png)

**Comment by KomeijiRan** [comment]
插件版本1.1.5-fix

**Comment by Nekoer** [comment]
请提供发不出来时候的log

**Comment by KomeijiRan** [comment]
[0m2022-07-15 12:37:10 V/Bot.340310984: [<$ÿĀ><$ÿĀ><$ÿĀ><$ÿĀ(218830532)] 镜水无澜(2270971241) -> /rss list[0m[m
[92m2022-07-15 12:37:10 I/BiliBiliCenter: 正在统计监控列表[0m[m
[0m2022-07-15 12:37:11 V/Bot.340310984: Group(218830532) <- [mirai:at:2270971241] 正在统计监控列表[0m[m
[0m2022-07-15 12:37:16 V/Bot.340310984: Group(218830532) <- ForwardMessage(preview=[墨雪: [图片]\n等级: Lv.6\n名字: 碧蓝航线\n简介: 今天有没有被指挥官偷瞄呢(:3_ヽ)_\n, 墨雪: [图片]\n等级: Lv.5\n名字: 碧蓝海事局\n简介: 碧蓝海事局是玩家自发建立的民间组织不是官方哦（ '▿ ' ）\n碧蓝航线WIKI：http://wiki.biligame.com/blhx/\n], title=正在监控的UP主们, brief=[聊天记录], source=聊天记录, summary=查看2条, nodeList=[Node(senderId=340310984, time=2456110, senderName=墨雪, messageChain=[mirai:image:{93AD2870-202E-4411-E336-E4C306EB65F6}.jpg]\n等级: Lv.6\n名字: 碧蓝航线\n简介: 今天有没有被指挥官偷瞄呢(:3_ヽ)_\n), Node(senderId=340310984, time=2456779, senderName=墨雪, messageChain=[mirai:image:{FDE1E948-95AD-8A01-BF65-58359845EF3D}.jpg]\n等级: Lv.5\n名字: 碧蓝海事局\n简介: 碧蓝海事局是玩家自发建立的民间组织不是官方哦（ '▿ ' ）\n碧蓝航线WIKI：http://wiki.biligame.com/blhx/\n)])[0m[m

[0m2022-07-15 12:40:10 V/Bot.340310984: [<$ÿĀ><$ÿĀ><$ÿĀ><$ÿĀ(218830532)] 镜水无澜(2270971241) -> /rss list[0m[m
[92m2022-07-15 12:40:10 I/BiliBiliCenter: 正在统计监控列表[0m[m
[0m2022-07-15 12:40:10 V/Bot.340310984: Group(218830532) <- [mirai:at:2270971241] 正在统计监控列表[0m[m
[0m2022-07-15 12:40:13 V/Bot.340310984: Group(218830532) <- ForwardMessage(preview=[墨雪: [图片]\n等级: Lv.6\n名字: 碧蓝航线\n简介: 今天有没有被指挥官偷瞄呢(:3_ヽ)_\n, 墨雪: [图片]\n等级: Lv.5\n名字: 碧蓝海事局\n简介: 碧蓝海事局是玩家自发建立的民间组织不是官方哦（ '▿ ' ）\n碧蓝航线WIKI：http://wiki.biligame.com/blhx/\n], title=正在监控的UP主们, brief=[聊天记录], source=聊天记录, summary=查看2条, nodeList=[Node(senderId=340310984, time=2635915, senderName=墨雪, messageChain=[mirai:image:{FDC51F3A-05B9-DBE9-3C72-902FDC9DB417}.jpg]\n等级: Lv.6\n名字: 碧蓝航线\n简介: 今天有没有被指挥官偷瞄呢(:3_ヽ)_\n), Node(senderId=340310984, time=2636539, senderName=墨雪, messageChain=[mirai:image:{A2BA072F-61EC-18E0-8066-D2D34191BA47}.jpg]\n等级: Lv.5\n名字: 碧蓝海事局\n简介: 碧蓝海事局是玩家自发建立的民间组织不是官方哦（ '▿ ' ）\n碧蓝航线WIKI：http://wiki.biligame.com/blhx/\n)])[0m[m

第一段是未能正常发出的log，完整log：https://wws.lanzoub.com/idGvO07usm7a
